# Generated by Django 5.2.6 on 2025-10-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemodels',
            old_name='lang_id',
            new_name='lang',
        ),
    ]
